
gracie = User.create({email: 'gracie@gracie.com', username: 'gracie', password: 'test'})

senators = Senator.create(
  [
    { name: 'Lamar Alexander',
     state: 'TN',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
   { name: 'Tammy Baldwin',
     state: 'WI',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'John Barrasso',
     state: 'WY',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
   },
   { name: 'Michael Bennet',
     state: 'CO',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Marsha Blackburn',
     state: 'TN',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
     },
     { name: 'Richard Blumenthal',
     state: 'CT',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Roy Blunt',
     state: 'MO',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Cory Booker',
     state: 'NJ',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'John Boozman',
     state: 'AR',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
   },
   { name: 'Mike Braun',
     state: 'IN',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
   },
   { name: 'Sherrod Brown',
     state: 'OH',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
   },
   { name: 'Richard Burr',
     state: 'NC',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
   },
   { name: 'Maria Cantwell',
     state: 'WA',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
   },
   { name: 'Shelley Moore Capito',
     state: 'WV',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
     },
   { name: 'Benjamin Cardin',
     state: 'MD',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Thomas Carper',
      state: 'DE',
      party: 'D',
      naacp_rating: '0',
      pp_rating: '0',
      envi_rating: '0',
      nra_rating: '0',
      trump_rating: '0',
      user_woke: false,
      user_joke: false,
      contact: ''
    },
    { name: 'Robert Casey Jr.',
     state: 'PA',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Bill Cassidy',
     state: 'LA',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Susan Collins',
     state: 'ME',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Christopher Coons',
     state: 'DE',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'John Cornyn',
     state: 'TX',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Catherine Cortex Masto',
     state: 'NV',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Tom Cotton',
     state: 'AR',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Kevin Cramer',
     state: 'ND',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Mike Crapo',
     state: 'ID',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Ted Cruz',
     state: 'TX',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Steve Daines',
     state: 'MT',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Tammy Duckworth',
     state: 'IL',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Richard Durbin',
     state: 'IL',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Michael Enzi',
     state: 'WY',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Joni Ernst',
     state: 'IA',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Dianne Feinstein',
     state: 'CA',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Deb Fischer',
     state: 'NE',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Cory Gardner',
     state: 'CO',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Kirsten Gillibrand',
     state: 'NY',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Lindsey Graham',
     state: 'SC',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Chuck Grassley',
     state: 'IA',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Kamala Harris',
     state: 'CA',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Margaret Wood Hassan',
     state: 'NH',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Josh Hawley',
     state: 'MO',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Martin Heinrich',
     state: 'NM',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Mazie Hirono',
     state: 'HI',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Joe Hoeven',
     state: 'ND',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Cindy Hyde-Smith',
     state: 'MS',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'James Inhofe',
     state: 'OK',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Johnny Isakson',
     state: 'GA',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Ron Johnson',
     state: 'WI',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Doug Jones',
     state: 'AL',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Tim Kaine',
     state: 'VA',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'John Kennedy',
     state: 'LA',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Angus King Jr.',
     state: 'ME',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Amy Klobuchar',
     state: 'MN',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'James Lankford',
     state: 'OK',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Patrick Leahy',
     state: 'VT',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Mike Lee',
     state: 'UT',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Joe Manchin III',
     state: 'WV',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Edward Markey',
     state: 'MA',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Mitch McConnell',
     state: 'KY',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Martha McSally',
     state: 'AZ',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Robert Menendez',
     state: 'NJ',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Jeff Merkley',
     state: 'OR',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Jerry Moran',
     state: 'KS',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Lisa Murkowski',
     state: 'AK',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Christopher Murphy',
     state: 'CT',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Patty Murray',
     state: 'WA',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Rand Paul',
     state: 'KY',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'David Perdue',
     state: 'GA',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Gary Peters',
     state: 'MI',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Rob Portman',
     state: 'OH',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Jack Reed',
     state: 'RI',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'James Risch',
     state: 'ID',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Pat Roberts',
     state: 'KS',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Mitt Romney',
     state: 'UT',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Jacky Rosen',
     state: 'NV',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Mike Rounds',
     state: 'SD',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Marco Rubio',
     state: 'FL',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Bernard Sanders',
     state: 'VT',
     party: 'I',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Ben Sasse',
     state: 'NE',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Brian Schatz',
     state: 'HI',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Charles Schumer',
     state: 'NY',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Tim Scott',
     state: 'SC',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Rick Scott',
     state: 'FL',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Jeanne Shaheen',
     state: 'NH',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Richard Shelby',
     state: 'AL',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Kyrsten Sinema',
     state: 'AZ',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Tina Smith',
     state: 'MN',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Debbier Stabenow',
     state: 'MI',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Dan Sullivan',
     state: 'AK',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Jon Tester',
     state: 'MT',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'John Thune',
     state: 'SD',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Thom Tillis',
     state: 'NC',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Patrick Toomey',
     state: 'PA',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Tom Udall',
     state: 'NM',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Chris Van Hollen',
     state: 'MD',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Mark Warner',
     state: 'VA',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Elizabeth Warren',
     state: 'MA',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Sheldon Whitehouse',
     state: 'RI',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Roger Wicker',
     state: 'MS',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Ron Wyden',
     state: 'OR',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    },
    { name: 'Todd Young',
     state: 'IN',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: ''
    }
  ]
)
