
gracie = User.create({email: 'gracie@gracie.com', username: 'gracie', password: 'test'})

senators = Senator.create(
  [
    { name: 'Lamar Alexander',
     state: 'TN',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: 'https://www.alexander.senate.gov/public/index.cfm/email',
     image: 'https://upload.wikimedia.org/wikipedia/commons/2/2b/Lamar_Alexander_official_photo.jpg'
    },
   { name: 'Tammy Baldwin',
     state: 'WI',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: 'https://www.baldwin.senate.gov/feedback',
     image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Tammy_Baldwin%2C_official_portrait%2C_113th_Congress.jpg/946px-Tammy_Baldwin%2C_official_portrait%2C_113th_Congress.jpg'
    },
    { name: 'John Barrasso',
     state: 'WY',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: 'https://www.barrasso.senate.gov/public/index.cfm/contact-form',
     image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/John_Barrasso_official_portrait_112th_Congress.jpg/440px-John_Barrasso_official_portrait_112th_Congress.jpg'
   },
   { name: 'Michael Bennet',
     state: 'CO',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: 'https://michaelbennet.com/about/',
     image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Michael_Bennet_Official_Photo.jpg/440px-Michael_Bennet_Official_Photo.jpg'
    },
    { name: 'Marsha Blackburn',
     state: 'TN',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: 'https://www.blackburn.senate.gov/contact_marsha',
     image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Sen._Marsha_Blackburn_%28R-TN%29_official_headshot_-_116th_Congress.jpg/440px-Sen._Marsha_Blackburn_%28R-TN%29_official_headshot_-_116th_Congress.jpg'
     },
     { name: 'Richard Blumenthal',
     state: 'CT',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: 'https://www.blumenthal.senate.gov/contact/',
     image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Richard_Blumenthal_Official_Portrait.jpg/1200px-Richard_Blumenthal_Official_Portrait.jpg'
    },
    { name: 'Roy Blunt',
     state: 'MO',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: 'https://www.blunt.senate.gov/contact/contact-roy',
     image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Roy_Blunt%2C_Official_Portrait%2C_112th_Congress.jpg/440px-Roy_Blunt%2C_Official_Portrait%2C_112th_Congress.jpg'
    },
    { name: 'Cory Booker',
     state: 'NJ',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: 'https://www.booker.senate.gov/?p=contact',
     image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Cory_Booker%2C_official_portrait%2C_114th_Congress.jpg/440px-Cory_Booker%2C_official_portrait%2C_114th_Congress.jpg'
    },
    { name: 'John Boozman',
     state: 'AR',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: 'https://www.boozman.senate.gov/public/index.cfm/contact',
     image: 'https://pbs.twimg.com/profile_images/970776346250104834/i7B-Xp9G_400x400.jpg'
   },
   { name: 'Mike Braun',
     state: 'IN',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
   },
   { name: 'Sherrod Brown',
     state: 'OH',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
   },
   { name: 'Richard Burr',
     state: 'NC',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
   },
   { name: 'Maria Cantwell',
     state: 'WA',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
   },
   { name: 'Shelley Moore Capito',
     state: 'WV',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
     },
   { name: 'Benjamin Cardin',
     state: 'MD',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Thomas Carper',
      state: 'DE',
      party: 'D',
      naacp_rating: '0',
      pp_rating: '0',
      envi_rating: '0',
      nra_rating: '0',
      trump_rating: '0',
      user_woke: false,
      user_joke: false,
      contact: '',
      image: ''
    },
    { name: 'Robert Casey Jr.',
     state: 'PA',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Bill Cassidy',
     state: 'LA',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Susan Collins',
     state: 'ME',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Christopher Coons',
     state: 'DE',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'John Cornyn',
     state: 'TX',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Catherine Cortex Masto',
     state: 'NV',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Tom Cotton',
     state: 'AR',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Kevin Cramer',
     state: 'ND',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Mike Crapo',
     state: 'ID',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Ted Cruz',
     state: 'TX',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Steve Daines',
     state: 'MT',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Tammy Duckworth',
     state: 'IL',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Richard Durbin',
     state: 'IL',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Michael Enzi',
     state: 'WY',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Joni Ernst',
     state: 'IA',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Dianne Feinstein',
     state: 'CA',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Deb Fischer',
     state: 'NE',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Cory Gardner',
     state: 'CO',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Kirsten Gillibrand',
     state: 'NY',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Lindsey Graham',
     state: 'SC',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Chuck Grassley',
     state: 'IA',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Kamala Harris',
     state: 'CA',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Margaret Wood Hassan',
     state: 'NH',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Josh Hawley',
     state: 'MO',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Martin Heinrich',
     state: 'NM',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Mazie Hirono',
     state: 'HI',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Joe Hoeven',
     state: 'ND',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Cindy Hyde-Smith',
     state: 'MS',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'James Inhofe',
     state: 'OK',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Johnny Isakson',
     state: 'GA',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Ron Johnson',
     state: 'WI',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Doug Jones',
     state: 'AL',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Tim Kaine',
     state: 'VA',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'John Kennedy',
     state: 'LA',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Angus King Jr.',
     state: 'ME',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Amy Klobuchar',
     state: 'MN',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'James Lankford',
     state: 'OK',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Patrick Leahy',
     state: 'VT',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Mike Lee',
     state: 'UT',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Joe Manchin III',
     state: 'WV',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Edward Markey',
     state: 'MA',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Mitch McConnell',
     state: 'KY',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Martha McSally',
     state: 'AZ',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Robert Menendez',
     state: 'NJ',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Jeff Merkley',
     state: 'OR',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Jerry Moran',
     state: 'KS',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Lisa Murkowski',
     state: 'AK',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Christopher Murphy',
     state: 'CT',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Patty Murray',
     state: 'WA',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Rand Paul',
     state: 'KY',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'David Perdue',
     state: 'GA',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Gary Peters',
     state: 'MI',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Rob Portman',
     state: 'OH',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Jack Reed',
     state: 'RI',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'James Risch',
     state: 'ID',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Pat Roberts',
     state: 'KS',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Mitt Romney',
     state: 'UT',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Jacky Rosen',
     state: 'NV',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Mike Rounds',
     state: 'SD',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Marco Rubio',
     state: 'FL',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Bernard Sanders',
     state: 'VT',
     party: 'I',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Ben Sasse',
     state: 'NE',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Brian Schatz',
     state: 'HI',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Charles Schumer',
     state: 'NY',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Tim Scott',
     state: 'SC',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Rick Scott',
     state: 'FL',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Jeanne Shaheen',
     state: 'NH',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Richard Shelby',
     state: 'AL',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Kyrsten Sinema',
     state: 'AZ',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Tina Smith',
     state: 'MN',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Debbier Stabenow',
     state: 'MI',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Dan Sullivan',
     state: 'AK',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Jon Tester',
     state: 'MT',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'John Thune',
     state: 'SD',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Thom Tillis',
     state: 'NC',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Patrick Toomey',
     state: 'PA',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Tom Udall',
     state: 'NM',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Chris Van Hollen',
     state: 'MD',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Mark Warner',
     state: 'VA',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Elizabeth Warren',
     state: 'MA',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Sheldon Whitehouse',
     state: 'RI',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Roger Wicker',
     state: 'MS',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Ron Wyden',
     state: 'OR',
     party: 'D',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    },
    { name: 'Todd Young',
     state: 'IN',
     party: 'R',
     naacp_rating: '0',
     pp_rating: '0',
     envi_rating: '0',
     nra_rating: '0',
     trump_rating: '0',
     user_woke: false,
     user_joke: false,
     contact: '',
     image: ''
    }
  ]
)
